In [1]:
import csv
import pandas as pd
import numpy as np
import os

# Create Flatfile

In [33]:
data = pd.read_csv('clean_data.csv', encoding = "ISO-8859-1", index_col = 0)

In [70]:
countries=data.index.tolist()
values = data.values.flatten().tolist()
headers=data.columns.tolist()
clean_headers=[]
for i in range(len(headers[1:])):
    new_list = headers[i+1].split("?")
    clean_headers.append(new_list)
clean_headers[0:2]
data_indices = []
for i in range(len(countries)):
    for j in range(len(clean_headers)):
        list_1 = clean_headers[j][0:5]
        list_1.append(countries[i])
        list_1 = list_1[-1:] + list_1[:-1]
        data_indices.append(list_1)
data_indices[0:5]
for i in range(len(values)):
    data_indices[i].append(values[i])
with open("output.csv", "wb") as f:
    writer = csv.writer(f)
    writer.writerows(data_indices)

In [99]:
df = pd.read_csv('output.csv', encoding = "ISO-8859-1", header=None)
df.columns =["countrs", "major_key", "key_1", "key_2", "key_3", "year", "value"]

# See What the keys are

In [103]:
print(df.major_key.unique())

['2. Population Size (Thousand)' '3. Coverage of WASH Services'
 '4. Total Population to be Served with New Services (Thousand, Per Year)'
 'Proportion of global unserved'
 '5. Unit Costs of WASH Services (Per Capita, US$)'
 '6. Coverage per Technology Type' '7. Economic Variables'
 '8. Costs of Extending to Unserved Population, by Year (2015 Prices, Thousand US$)'
 '9. Summary WASH Costs of Extending to Unserved Population (2015 Prices, Thousands))'
 '10. Capital Costs as a Percent of GDP'
 '11. Cost Breakdown by Capital, Capital Maintenance and Operational (Annual Values, Average for 2015 to target year)'
 '11. Cost per person per year at PPP values'
 '12. Cost as % of $1.90 poverty income in 2011, adjusted to 2015 figure']

In [104]:
print(df.key_1.unique())

['blank' 'Basic water supply within 30 minutes (no water quality)'
 'Safely managed water supply at home'
 'Current JMP improved sanitation definition (private only)'
 'Population with Any Fixed Point Defecation'
 'Safely managed fecal sludge' 'Handwashing station, soap & water at home'
 'Basic Water' 'Open defecation (Population to Serve)' 'Basic Sanitation'
 'Basic Hygiene' 'Safely Managed Water' 'Safely Managed Sanitation'
 'Water' 'Sanitation' 'Wat + San' 'Basic Water Supply'
 'Safely managed water supply' 'Unimproved Sanitation (ODF)'
 'Safely managed sanitation (incremental only)' 'Handwashing'
 'Ending Open Defecation' 'Advanced Water' 'Safe Fecal Management'
 'Basic WASH' 'Basic & Advanced Water'
 'Basic Sanitation & Fecal Sludge Management'
 'Basic WASH and Advanced WatSan Services' 'Full Fecal Sludge Management'
 'Safe Water 100% (Incremental)' 'Safe Sanitation 100% (Incremental Cost)'
 'Safe Water 50% (Incremental)' 'TOTAL GDP (US$ Million)' 'Total Costs'
 'Proportion of GDP' 'Open Defecation Free' 'Safe Services'
 'Basic WASH Cost (Annual)'
 'Safe water, adequate sanitation, FSM. Handwashing']

In [105]:
print(df.key_2.unique())

['Urban' 'Rural' 'Basic Urban Water' 'Basic Rural Water' 'Rural ODF'
 'Basic Urban Sanitation' 'Basic Urban Hygiene' 'Basic Rural Hygiene'
 'Safely managed Urban Water' 'Safely Managed Rural Water'
 'Safely Managed Urban Sanitation' 'Safely Managed Rural Sanitation' '%'
 'Urban Tubewell' 'Urban Dug Well' 'Rural Tubewell' 'Rural Dug Well'
 'Urban - septic tank' 'Urban - any pit latrine' 'Rural - wet pit latrine'
 'Rural - dry pit latrine' 'Rural Unimproved Pit Latrine'
 'Urban - sewerage with treatment (incremental cost only)'
 'Urban - septic tank with FSM (incremental cost only)'
 'Rural - pit latrine with FSM (incremental cost only)'
 'Rural - pit latrine with sewerage and treatment (incremental cost only)'
 'GDP Values' 'Human Capital' 'Value for VSL calculation' 'DALY Value'
 'Value-of-statistical-life' 'Value of time, as % of unit of value'
 'Poverty' 'Discount rate' 'Total' 'Universal Basic (USD Millions)'
 'Universal Safe (USD Millions)' 'Universal Basic (%)'
 'Universal Safe (%)' 'Water' 'Sanitation' 'Hygiene' 'Safe Water'
 'Safe Sanitation']

In [115]:
print(df.key_3.unique())

['blank' 'Coverage in 2015' 'Target Year' 'Coverage in target year'
 'Households Connected in 2015'
 'Proportion of Collected Sewage Treated 2015'
 'Non-connected households with safely managed fecal sludge'
 'Effective treatment (either sewerage or FSM)' 'Forecast for 2015'
 'Q5 (Richest)' 'Q4' 'Q3' 'Q2' 'Q1 (Poorest)' 'Total' 'Q5 (Rich)'
 'Q1 (Poor)' 'Annual Total' 'All Quintiles' 'New facility / replacement'
 'Maintenance' 'Annual' 'Total Annualized' '1' 'Tubewell or Borehole'
 'Dug well' 'Septic tank' 'Any pit latrine' 'Wet pit latrine'
 'Dry pit latrine' 'Sewerage with treatment' 'Septic tank with FSM'
 '(Dry) pit latrine with FSM' 'Actual (US$)' 'Average wage' 'Minimum wage'
 'PPP Value (I$)' 'Adult (40 years productive life)' 'VSL DALY 1000, 3%'
 'VSL DALY 1000, 5%' 'VSL DALY 5000, 3%' 'VSL DALY 5000, 5%'
 'VSL to be used for benefits transfer (in US$)'
 'GDP per capita of VSL source country, US$' 'VSL Value (US$) in 2015'
 '0-4 yrs' '5-14 yrs' '15+ yrs' 'Working days per year'
 'Poverty Line, US$ 1.9 per day PPP at 2015 prices' '0.05'
 'All Wealth Quintiles' 'Urban' 'Rural' 'Low technology' 'High technology']

In [109]:
print(df.year.unique())

['2015' '2016' '2017' '2018' '2019' '2020' '2021' '2022' '2023' '2024'
 '2025' '2026' '2027' '2028' '2029' '2030' '2030 data' 'All population'
 'Q5 (Rich)' 'Q4' 'Q3' 'Q2' 'Q1 (Poor)' '2015-2019' '2020-2024'
 '2025-2029' '2015-2029' 'Annual until target year' 'Total' 'CapEx'
 'Software' 'Software (% of Capex)' 'Duration' 'Annualized' 'CapManEx %'
 'CapManEx' 'OpEx' 'Software %' 'Av. No. of HHs Sharing'
 'Duration Hardware' 'Duration Software' 'Urban' 'Rural' '37000' '31000'
 '185000' '155000' 'Capital' 'Cap. Replace (10)' 'Cap Replace (8)'
 'Av. Annual' 'Year 2015' 'Ending OD' 'Water' 'Sanitation' 'Hygiene'
 'WASH' 'WatSan' 'Targets 6.1 + 6.2' 'Capital maintenance' 'Operations'
 'Capital / SW' 'O&M']

## Check a Year

In [141]:
data_2017 = df[df['year'] =='2015']
data_2017.head(n=20)

,countrs,major_key,key_1,key_2,key_3,year,value
0,Afghanistan,2. Population Size (Thousand),blank,Urban,blank,2015,8546.635
17,Afghanistan,2. Population Size (Thousand),blank,Rural,blank,2015,23460.153
118,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Urban Water,Q5 (Richest),2015,133.0097993
137,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Urban Water,Q4,2015,133.0150997
156,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Urban Water,Q3,2015,133.177573
175,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Urban Water,Q2,2015,134.069166
194,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Urban Water,Q1 (Poorest),2015,135.341639
213,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Urban Water,Total,2015,668.6132771000001
232,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Rural Water,Q5 (Richest),2015,207.6962918
251,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Rural Water,Q4,2015,221.62095719999996
270,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Rural Water,Q3,2015,229.6329864
289,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Rural Water,Q2,2015,242.9449347
308,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Rural Water,Q1 (Poorest),2015,266.8303815
327,Afghanistan,4. Total Population to be Served with New Serv...,Basic Water,Basic Rural Water,Total,2015,1168.7255519999999
353,Afghanistan,4. Total Population to be Served with New Serv...,Basic Sanitation,Basic Urban Sanitation,Q5 (Richest),2015,140.3905409
372,Afghanistan,4. Total Population to be Served with New Serv...,Basic Sanitation,Basic Urban Sanitation,Q4,2015,141.1825562
391,Afghanistan,4. Total Population to be Served with New Serv...,Basic Sanitation,Basic Urban Sanitation,Q3,2015,141.91167240000001
410,Afghanistan,4. Total Population to be Served with New Serv...,Basic Sanitation,Basic Urban Sanitation,Q2,2015,142.7762121
429,Afghanistan,4. Total Population to be Served with New Serv...,Basic Sanitation,Basic Urban Sanitation,Q1 (Poorest),2015,146.0838433
448,Afghanistan,4. Total Population to be Served with New Serv...,Basic Sanitation,Basic Urban Sanitation,Total,2015,712.344825

## Look at current access 
### all
Almost all countries are in Africa, and all rural areas unsurprisingly

In [144]:
df_safe_water = df[(df['major_key'] =='3. Coverage of WASH Services') & (df['year'] =='All population') & (df['key_1'] == 'Safely managed water supply at home')]
df_safe_water=df_safe_water.sort_values(by=['value'])
df_safe_water.head(n=20)

,countrs,major_key,key_1,key_2,key_3,year,value
458458,Marshall Islands,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0
103962,Burkina Faso,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.000124734
250650,Eritrea,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.000150013
311770,Guinea-Bissau,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.000593448
757946,Togo,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.000684878
672378,Sierra Leone,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0009299060000000001
140634,Chad,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0009681080000000001
415674,Liberia,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.001015314
507354,Mozambique,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.001102392
305658,Guinea,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0013375779999999999
110074,Burundi,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0014244639999999999
544026,Niger,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.001682111
18394,Angola,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0020757270000000003
550138,Nigeria,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.002078347
244538,Equatorial Guinea,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.00230724
843514,Zambia,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.002530108
684602,Somalia,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0027156990000000002
794618,Uganda,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0029426509999999997
256762,Ethiopia,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.003015243
42842,Bangladesh,3. Coverage of WASH Services,Safely managed water supply at home,Rural,Coverage in 2015,All population,0.0030966270000000002

In [145]:
df_safe_water_urban= df_safe_water[df_safe_water['key_2']=="Urban"]
df_safe_water_urban=df_safe_water_urban.sort_values(by=['value'])
df_safe_water_urban.head(n=20)

,countrs,major_key,key_1,key_2,key_3,year,value
134514,Central African Republic,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.015757221000000002
415666,Liberia,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.022768347
550130,Nigeria,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.023597378999999998
458450,Marshall Islands,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.038078399
672370,Sierra Leone,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.040287399
311762,Guinea-Bissau,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.050475146
757938,Togo,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.053058361
427890,Madagascar,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.086501047
140626,Chad,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.08876527599999999
323986,Haiti,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.10689140400000001
623474,Rwanda,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.121298512
507346,Mozambique,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.12349773800000001
50,Afghanistan,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.125141145
794610,Uganda,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.1462781
244530,Equatorial Guinea,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.146464499
103954,Burkina Faso,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.14692851199999998
806834,Un. Rep. Tanzania,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.15488443
18386,Angola,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.164552724
122290,Cameroon,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.16795407699999998
434002,Malawi,3. Coverage of WASH Services,Safely managed water supply at home,Urban,Coverage in 2015,All population,0.173264516